version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_DATABASE: "cursossymfony2"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
  mailer:
    image: schickling/mailcatcher
    ports: 
      - "1025:1080"
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - db

  rabbitmq:
      image: rabbitmq:3.7-management
      ports: [5672, 15672]