#index:
#    path: /
#    controller: App\Controller\DefaultController::index


homepage:
  path: /
  controller: App\Controller\ConferenceController::index

admin:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index

conference:
  path: /conference/{id}
  controller: App\Controller\ConferenceController::show
  methods: GET